### ISSUE TITLE
下载后打开首页无法安装

### ISSUE THREAD

**Issue by dongnanyanhai** [hubinjie/ACI#1]
下载后打开首页无法安装，

通过地址栏访问：http://域名/setup/setp/index 得到404错误

**Comment by hubinjie** [comment]
是什么运行环境？支不支持.htacess?

**Comment by dongnanyanhai** [comment]
使用的php环境是：upupw 套件，apache 2.4 、php5.3，我再试试！

支持.htacess

把程序放到一个独立域名下了，有在config目录下的database.php设定数据库账号和密码。

**Comment by hubinjie** [comment]
嗯嗯，之前在 修正lib的命名不规范，导致Linux下不能用 ,会有些BUG，刚有一个朋友修复了一下。

**Comment by dongnanyanhai** [comment]
github上的配置文件是已经安装后的，需要修改application\config目录下的aci文件，修改域名和把installED改为false，才会自动跳转到安装页面。

$config['base_url'] = '';
$config['aci_status'] = array (
  'systemVersion' => '1.0.0',
  'installED' => false,
);

另外CI框架出现了下面错误，从网上找的资料看，应该是“Session”库写入文件出现权限问题。
Severity: Warning
Message:touch(): open_basedir restriction in effect. 

修改了application\config\config.php 文件里的$config['sess_save_path'] = 'SESSION';设置依然没能解决问题。

网站根目录有自动生成SESSION目录，但似乎读取的时候又不在该目录下读取SESSION。

**Comment by dongnanyanhai** [comment]
在application\config\config.php 中设定$config['sess_save_path'] 的值为绝对路径后解决问题。
