### ISSUE TITLE
进入后台页面，输入用户名密码，无法点击登陆

### ISSUE THREAD

**Issue by YuyangHYY** [hubinjie/ACI#19]
<img width="785" alt="2018-05-10 11 28 34" src="https://user-images.githubusercontent.com/19391002/39850702-63503390-5445-11e8-8cfb-66243209a786.png">
<img width="812" alt="2018-05-10 11 23 43" src="https://user-images.githubusercontent.com/19391002/39850712-6a9a1134-5445-11e8-88bb-f6daa318f073.png">

**Comment by Liaboo** [comment]
![image](https://user-images.githubusercontent.com/26105430/39918461-1589215e-5543-11e8-83e6-99a153ed6862.png)

**Comment by YuyangHYY** [comment]
@Liaboo 你好，我是用的mamp，这边的路径需要修改么？

**Comment by YuyangHYY** [comment]
问题已解决，我用的mamp，放在htdocs初始目录。
在**application -> config.php -> constants.php** 修改 `define("'SITE_URL', '/对应初始目录文件的文件名/'")`
<img width="984" alt="2018-06-06 12 35 42" src="https://user-images.githubusercontent.com/19391002/41017151-378e5dee-6986-11e8-9561-5dd89c5cebf4.png">
登陆页面读取成功，登陆按键不能点击问题已解决
<img width="837" alt="2018-06-06 12 35 52" src="https://user-images.githubusercontent.com/19391002/41017163-40ecc128-6986-11e8-82e4-0498086f0c2e.png">
