### ISSUE TITLE
登陆无法跳转

### ISSUE THREAD

**Issue by ghost** [hubinjie/ACI#7]
wamp环境，chrome浏览器，登陆无法跳转，提示登陆中，请稍后，没有提示登陆成功提示。然后登陆按钮也处于不可用的状态。手工输入后台路径，又可以访问。是怎么回事？

**Comment by hubinjie** [comment]
看一下chrome中开发者工具看一下有没有脚本报错？

**Comment by ghost** [comment]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
jQuery.js

**Comment by ghost** [comment]
网上有人说这个报错是服务器配置的问题，缺少了能够解析json的配置信息，导致浏览器向服务器发出请求时，服务器不能处理html文件里面的js引用，所以一直在loading状态，而不能返回html页面。
解决方案是在nginx的配置信息里加入下面的配置信息：
location ~\* .(jpg|gif|png|js|css)$ {
        root 你自己的文件路径;
         if (-f $request_filename) {
                 expires max;
                 break;
                 }
 }
但是没有给Apache的解决方案，对于Apache不知道你有没有什么好的解决方案？

**Comment by hubinjie** [comment]
本身开发环境就是apache，你是用chrome 多少版本的？换个浏览器还是一样吗？

**Comment by ghost** [comment]
你好，我的chrome版本是最新的46.0.2490.80
换了Firefox和Edge问题都是一样的。

**Comment by ghost** [comment]
应该是这个wamp环境需要做一个什么配置，不然解析不到json数据。

**Comment by ghost** [comment]
谢谢你！重新安装了wamp就可以了，应该之前安装的丢了什么模块。

**Comment by hubinjie** [comment]
好的
